version: '3'

services:
  web:
    build: .
    restart: always
    container_name: web
    command: sh -c "export DJANGO_SETTINGS_MODULE=project.settings.prod &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/automatica
    ports:
      - "0.0.0.0:8000:8000"
    env_file:
      - .env

  db:
    image: postgres
    container_name: pgdb
    env_file:
      - .env
    volumes:
      - dbdata:/var/lib/postgresql/data/

volumes:
    dbdata: {}