# Generated by Django 3.2.7 on 2022-01-10 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_store_worker'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
